version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-latest"
  jobs:
    pre_build:
      - source "./igraphviz_flowcharts/create_svg.sh"
      - python ./igraphviz_flowcharts/remove_tooltip.py
      - python check_tab_ref.py 

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  # Fail on all warnings to avoid broken references
  fail_on_warning: true

# Explicitly set the version of Python and its requirements
conda:
  environment: conda_dev_env.yml
