version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-latest"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  # Fail on all warnings to avoid broken references
  fail_on_warning: true

# Explicitly set the version of Python and its requirements
conda:
  environment: conda_dev_env.yml
