version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-latest"
  jobs:
    post_build:
      - dot -Tsvg ./igraphviz_flowcharts/dot_files/getting_started_hpc_flowchart.dot > ./igraphviz_flowcharts/generated_images/getting_started_hpc_flowchart.svg
      - dot -Tsvg ./igraphviz_flowcharts/dot_files/getting_started_cloud_flowchart.dot ./igraphviz_flowcharts/generated_images/getting_started_cloud_flowchart.svg
      - python ./igraphviz_flowcharts/remove_tooltip.py
      - python check_tab_ref.py 

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  # Fail on all warnings to avoid broken references
  fail_on_warning: true

# Explicitly set the version of Python and its requirements
conda:
  environment: conda_dev_env.yml
