name: rc-docs
channels:
  - conda-forge
dependencies:
  - python==3.14.6
  - sphinx==9.1.0
  - myst-parser==5.1.0
  - graphviz==14.1.2
  - pip
  - pip:
    - sphinx-book-theme==1.2.0
    - sphinx-copybutton==0.5.2
    - lxml==6.1.1
    - sphinx-design==0.7.0
