name: rc-docs
channels:
  - conda-forge
dependencies:
  - python==3.11.9
  - sphinx==7.3.7 
  - myst-parser==3.0.1
  - graphviz==12.0.0
  - pip
  - pip:
    - sphinx-book-theme==1.1.3
    - sphinx-copybutton==0.5.2
    - sphinx-togglebutton==0.3.2
    - lxml==5.3.0
    - sphinx-design==0.6.1